import * as THREE from 'three';
import { FontLoader } from 'three/examples/jsm/loaders/FontLoader.js';
import { TextGeometry } from 'three/examples/jsm/geometries/TextGeometry.js';
import './style.css';

const POSTER_W = 1080;
const POSTER_H = 1350;
const HALF_W = POSTER_W / 2;
const HALF_H = POSTER_H / 2;
const SAFE_MARGIN = 86;
const SCALE = 0.56;
const VIDEO_DURATION_MS = 6000;

const stage = document.querySelector('#stage');
const renderer = new THREE.WebGLRenderer({ antialias: true, preserveDrawingBuffer: true, alpha: false });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.setSize(POSTER_W * SCALE, POSTER_H * SCALE);
renderer.shadowMap.enabled = true;
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.domElement.setAttribute('aria-label', 'Poster canvas: drag text and sketch layers');
stage.appendChild(renderer.domElement);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(28, POSTER_W / POSTER_H, 1, 5000);
camera.position.set(0, 0, 1850);
scene.add(new THREE.AmbientLight(0xffffff, 1.55));
const key = new THREE.DirectionalLight(0xfff2df, 4.2); key.position.set(-300,420,900); scene.add(key);
const rim = new THREE.DirectionalLight(0xff48c4,3.2); rim.position.set(600,-180,700); scene.add(rim);

const bgCanvas=document.createElement('canvas'); bgCanvas.width=POSTER_W; bgCanvas.height=POSTER_H;
const bgTexture=new THREE.CanvasTexture(bgCanvas); bgTexture.colorSpace=THREE.SRGBColorSpace;
const bg=new THREE.Mesh(new THREE.PlaneGeometry(POSTER_W,POSTER_H),new THREE.MeshBasicMaterial({map:bgTexture})); bg.position.z=-180; bg.userData.nonInteractive=true; scene.add(bg);
const palettes={amore:['#240812','#6d173b','#b77cff'],acid:['#08170d','#31ff70','#fb38ff'],night:['#03020a','#1b1456','#215dff'],sunset:['#32101d','#ff4a1a','#ffb65c']};
const bgState={colors:[...palettes.amore],angle:135};
function updateBackground(){const ctx=bgCanvas.getContext('2d'),rad=THREE.MathUtils.degToRad(bgState.angle),cx=bgCanvas.width/2,cy=bgCanvas.height/2,len=Math.hypot(bgCanvas.width,bgCanvas.height)/2;const grad=ctx.createLinearGradient(cx-Math.cos(rad)*len,cy-Math.sin(rad)*len,cx+Math.cos(rad)*len,cy+Math.sin(rad)*len);grad.addColorStop(0,bgState.colors[0]);grad.addColorStop(.52,bgState.colors[1]);grad.addColorStop(1,bgState.colors[2]);ctx.fillStyle=grad;ctx.fillRect(0,0,bgCanvas.width,bgCanvas.height);bgTexture.needsUpdate=true;} updateBackground();

const fields={
 logo:{label:'MORE AMORE TEXT',text:' ',size:52,depth:18,x:0,y:470,scaleX:1,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:3,metalness:.15,roughness:.3,color:'#fff1dc',animation:'none',animSpeed:1,animAmount:18},
 guest:{label:'GUEST',text:'GUEST NAME',size:58,depth:24,x:0,y:250,scaleX:.9,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:4,metalness:.25,roughness:.2,color:'#b77cff',animation:'none',animSpeed:1,animAmount:24},
 support1:{label:'SUPPORT 1',text:'AURORA',size:34,depth:12,x:0,y:100,scaleX:1,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:2.5,metalness:.05,roughness:.4,color:'#f5ead8',animation:'none',animSpeed:1,animAmount:18},
 support2:{label:'SUPPORT 2',text:'OLIVIA',size:34,depth:12,x:0,y:25,scaleX:1,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:2.5,metalness:.05,roughness:.4,color:'#f5ead8',animation:'none',animSpeed:1,animAmount:18},
 venue:{label:'VENUE',text:'CLUB NAME',size:40,depth:14,x:0,y:-145,scaleX:1,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:3,metalness:.15,roughness:.28,color:'#ff4a1a',animation:'none',animSpeed:1,animAmount:18},
 address:{label:'ADDRESS',text:'VIA INDIRIZZO, CITTÀ',size:20,depth:7,x:0,y:-235,scaleX:1,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:1.5,metalness:.1,roughness:.45,color:'#ff4a1a',animation:'none',animSpeed:1,animAmount:14},
 date:{label:'DATE',text:'DAY 00 MONTH',size:30,depth:12,x:-300,y:-480,scaleX:1,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:2.5,metalness:.2,roughness:.28,color:'#b77cff',animation:'none',animSpeed:1,animAmount:16},
 time:{label:'TIME',text:'00:00 — 00:00',size:20,depth:7,x:-300,y:-550,scaleX:1,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:1.5,metalness:.05,roughness:.4,color:'#f5ead8',animation:'none',animSpeed:1,animAmount:12}
};

let artistCounter=0,infoCounter=0,sketchCounter=0,font; const meshes={}; let selected='guest'; const clock=new THREE.Clock();
function makeMaterial(cfg){return new THREE.MeshStandardMaterial({color:cfg.color,metalness:cfg.metalness,roughness:cfg.roughness});}
function buildGeometry(cfg){const g=new TextGeometry(cfg.text,{font,size:cfg.size,depth:cfg.depth,curveSegments:10,bevelEnabled:cfg.bevel>0,bevelThickness:cfg.bevel*.65,bevelSize:cfg.bevel,bevelSegments:4});g.computeBoundingBox();const bb=g.boundingBox,w=bb.max.x-bb.min.x,h=bb.max.y-bb.min.y;g.translate(-bb.min.x-w/2,-bb.min.y-h/2,0);const pos=g.attributes.position,denom=Math.max(w*w,1);for(let i=0;i<pos.count;i++){const x=pos.getX(i),y=pos.getY(i);pos.setY(i,y+cfg.bend*((x*x)/denom)*260);}pos.needsUpdate=true;g.computeVertexNormals();g.computeBoundingBox();return g;}
function getTextHalfExtents(id){const mesh=meshes[id];if(!mesh||!mesh.geometry.boundingBox)return{x:40,y:20};const bb=mesh.geometry.boundingBox;return{x:Math.max(10,(bb.max.x-bb.min.x)*Math.abs(fields[id].scaleX)/2),y:Math.max(10,(bb.max.y-bb.min.y)*Math.abs(fields[id].scaleY)/2)};}
function clampFieldToPoster(id){const cfg=fields[id],e=getTextHalfExtents(id);const maxX=Math.max(0,HALF_W-SAFE_MARGIN-Math.min(e.x,HALF_W-SAFE_MARGIN)),maxY=Math.max(0,HALF_H-SAFE_MARGIN-Math.min(e.y,HALF_H-SAFE_MARGIN));cfg.x=THREE.MathUtils.clamp(cfg.x,-maxX,maxX);cfg.y=THREE.MathUtils.clamp(cfg.y,-maxY,maxY);}
function rebuild(id){if(!font||!fields[id])return;const cfg=fields[id];if(meshes[id]){scene.remove(meshes[id]);meshes[id].geometry.dispose();meshes[id].material.dispose();}const mesh=new THREE.Mesh(buildGeometry(cfg),makeMaterial(cfg));mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.layerId=id;mesh.renderOrder=10;meshes[id]=mesh;scene.add(mesh);clampFieldToPoster(id);applyBaseTransform(id);}
function applyBaseTransform(id){const cfg=fields[id],mesh=meshes[id];if(!mesh||!cfg)return;mesh.position.set(cfg.x,cfg.y,0);mesh.rotation.set(THREE.MathUtils.degToRad(cfg.rotX),0,THREE.MathUtils.degToRad(cfg.rotZ));mesh.scale.set(cfg.scaleX,cfg.scaleY,1);}
function rebuildAll(){Object.keys(fields).forEach(rebuild);}

const logoState={group:null,texture:null,width:480,height:190,depth:28,scale:1,x:0,y:455,animation:'none',animSpeed:1,animAmount:20};
function disposeGroup(group){if(!group)return;group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m?.dispose?.());else if(o.material)o.material.dispose();});scene.remove(group);}
function disposeLogo(){disposeGroup(logoState.group);logoState.group=null;}
function buildLogo(){if(!logoState.texture)return;disposeLogo();const group=new THREE.Group();group.userData.fixedLogo=true;const sideMaterial=new THREE.MeshStandardMaterial({color:'#5a244a',metalness:.45,roughness:.24}),invisible=new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false});const shell=new THREE.Mesh(new THREE.BoxGeometry(logoState.width,logoState.height,Math.max(2,logoState.depth)),[sideMaterial,sideMaterial,sideMaterial,sideMaterial,invisible,invisible]);shell.position.z=-logoState.depth/2;group.add(shell);const slices=Math.max(4,Math.round(logoState.depth/2));for(let i=slices;i>=1;i--){const m=new THREE.MeshBasicMaterial({map:logoState.texture,transparent:true,alphaTest:.03,color:'#6f315d',side:THREE.DoubleSide,depthWrite:true});const layer=new THREE.Mesh(new THREE.PlaneGeometry(logoState.width,logoState.height),m);layer.position.z=-i*(logoState.depth/slices);group.add(layer);}const front=new THREE.Mesh(new THREE.PlaneGeometry(logoState.width,logoState.height),new THREE.MeshBasicMaterial({map:logoState.texture,transparent:true,alphaTest:.03,color:'#ffffff',side:THREE.DoubleSide}));front.position.z=1;group.add(front);logoState.group=group;scene.add(group);applyLogoBase();}
function applyLogoBase(){if(!logoState.group)return;logoState.group.position.set(logoState.x,logoState.y,55);logoState.group.scale.setScalar(logoState.scale);}

const PARTNER_GAP=22,PARTNER_PLANE_Z=-145,PARTNER_BOTTOM_MARGIN=92,PARTNER_RIGHT_MARGIN=86;
const partnerStates=[{group:null,texture:null,width:132,height:74,x:0,y:0},{group:null,texture:null,width:132,height:74,x:0,y:0}];
function layoutPartnerLogos(){const active=partnerStates.filter(s=>s.texture);if(!active.length)return;const bottomY=-HALF_H+PARTNER_BOTTOM_MARGIN;let rightEdge=HALF_W-PARTNER_RIGHT_MARGIN;for(let i=partnerStates.length-1;i>=0;i--){const s=partnerStates[i];if(!s.texture)continue;const hw=s.width/2,hh=s.height/2;s.x=rightEdge-hw;s.y=bottomY+hh;rightEdge=s.x-hw-PARTNER_GAP;if(s.group)s.group.position.set(s.x,s.y,PARTNER_PLANE_Z);}}
function buildPartnerLogo(index){const s=partnerStates[index];if(!s.texture)return;disposeGroup(s.group);const group=new THREE.Group(),mesh=new THREE.Mesh(new THREE.PlaneGeometry(s.width,s.height),new THREE.MeshBasicMaterial({map:s.texture,transparent:true,alphaTest:.01,side:THREE.DoubleSide,depthTest:false,depthWrite:false,toneMapped:false}));mesh.renderOrder=100;group.add(mesh);group.renderOrder=100;s.group=group;scene.add(group);layoutPartnerLogos();}
function loadImageAsTexture(file,maxW,maxH,onReady){const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{const ratio=Math.min(maxW/image.naturalWidth,maxH/image.naturalHeight,1),texture=new THREE.Texture(image);texture.colorSpace=THREE.SRGBColorSpace;texture.needsUpdate=true;onReady({texture,width:image.naturalWidth*ratio,height:image.naturalHeight*ratio});URL.revokeObjectURL(url);};image.src=url;}
const sketchStates=[],sketchList=document.querySelector('#sketchList');
function clampImageState(state){const hw=Math.min(state.width*state.scale/2,HALF_W-SAFE_MARGIN),hh=Math.min(state.height*state.scale/2,HALF_H-SAFE_MARGIN);state.x=THREE.MathUtils.clamp(state.x,-HALF_W+SAFE_MARGIN+hw,HALF_W-SAFE_MARGIN-hw);state.y=THREE.MathUtils.clamp(state.y,-HALF_H+SAFE_MARGIN+hh,HALF_H-SAFE_MARGIN-hh);}
function buildSketch(state){if(state.group)disposeGroup(state.group);const group=new THREE.Group();group.userData.sketchId=state.id;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(state.width,state.height),new THREE.MeshBasicMaterial({map:state.texture,transparent:true,alphaTest:.01,side:THREE.DoubleSide,depthTest:false}));mesh.userData.sketchId=state.id;mesh.renderOrder=35;group.add(mesh);state.group=group;clampImageState(state);group.position.set(state.x,state.y,65);group.scale.setScalar(state.scale);scene.add(group);}
function addSketchListItem(state){const row=document.createElement('div');row.className='sketch-item';row.dataset.sketchId=state.id;row.innerHTML=`<span>${state.name}</span><button type="button" title="Remove sketch">×</button>`;row.querySelector('button').onclick=()=>{if(state.group)disposeGroup(state.group);if(state.texture)state.texture.dispose();const idx=sketchStates.findIndex(s=>s.id===state.id);if(idx>=0)sketchStates.splice(idx,1);row.remove();};sketchList.appendChild(row);}
function addSketchFile(file){loadImageAsTexture(file,360,360,({texture,width,height})=>{const index=sketchCounter++,state={id:`sketch-${Date.now()}-${index}`,name:file.name||`Sketch ${index+1}`,texture,width,height,scale:1,x:-280+(index%3)*120,y:160-(index%4)*95,group:null};sketchStates.push(state);buildSketch(state);addSketchListItem(state);});}
document.querySelector('#sketchUpload').addEventListener('change',e=>{[...(e.target.files||[])].forEach(addSketchFile);e.target.value='';});
function animateObject(obj,cfg,t,isLogo=false){if(!obj)return;const speed=cfg.animSpeed||1,amount=cfg.animAmount||20;if(isLogo){obj.position.set(cfg.x,cfg.y,55);obj.rotation.set(0,0,0);obj.scale.setScalar(cfg.scale);}else{obj.position.set(cfg.x,cfg.y,0);obj.rotation.x=THREE.MathUtils.degToRad(cfg.rotX);obj.rotation.y=0;obj.rotation.z=THREE.MathUtils.degToRad(cfg.rotZ);obj.scale.set(cfg.scaleX,cfg.scaleY,1);}if(cfg.animation==='rotateY')obj.rotation.y=t*speed*1.6;else if(cfg.animation==='bounce')obj.position.y=cfg.y+Math.abs(Math.sin(t*speed*2.5))*amount;else if(cfg.animation==='wave'){obj.rotation.z+=Math.sin(t*speed*2.2)*THREE.MathUtils.degToRad(amount*.35);obj.position.y=cfg.y+Math.sin(t*speed*3.2)*amount*.45;if(!isLogo)obj.scale.y*=1+Math.sin(t*speed*4)*Math.min(amount/500,.14);}}
function render(){const t=clock.getElapsedTime();Object.entries(meshes).forEach(([id,mesh])=>fields[id]&&animateObject(mesh,fields[id],t));if(logoState.group)animateObject(logoState.group,logoState,t,true);renderer.render(scene,camera);requestAnimationFrame(render);}
const fieldsEl=document.querySelector('#fields');
function addFieldButton(id){const cfg=fields[id];if(!cfg)return;const b=document.createElement('button');b.className='field-btn';b.dataset.id=id;b.innerHTML=`<span>${cfg.label}</span><span class="field-key">${id}</span>`;b.onclick=()=>selectLayer(id);fieldsEl.appendChild(b);}Object.keys(fields).forEach(addFieldButton);
function createDynamicField(type){const isArtist=type==='artist',n=isArtist?++artistCounter:++infoCounter,id=`${type}${Date.now()}${n}`,rowOffset=((artistCounter+infoCounter-1)%6)*48;fields[id]=isArtist?{label:`ARTISTA ${n}`,text:`ARTISTA ${n}`,size:41,depth:14,x:0,y:145-rowOffset,scaleX:1,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:2.5,metalness:.08,roughness:.38,color:'#f5ead8',animation:'none',animSpeed:1,animAmount:18}:{label:`INFO ${n}`,text:`INFO ${n}`,size:24,depth:8,x:0,y:-285-rowOffset,scaleX:1,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:1.5,metalness:.04,roughness:.5,color:'#f5ead8',animation:'none',animSpeed:1,animAmount:12};addFieldButton(id);if(font)rebuild(id);selectLayer(id);}
document.querySelector('#addArtist').addEventListener('click',()=>createDynamicField('artist'));document.querySelector('#addInfo').addEventListener('click',()=>createDynamicField('info'));
const controls={text:document.querySelector('#textInput'),size:document.querySelector('#size'),depth:document.querySelector('#depth'),x:document.querySelector('#x'),y:document.querySelector('#y'),scaleX:document.querySelector('#scaleX'),scaleY:document.querySelector('#scaleY'),rotZ:document.querySelector('#rotZ'),rotX:document.querySelector('#rotX'),bend:document.querySelector('#bend'),bevel:document.querySelector('#bevel'),metalness:document.querySelector('#metalness'),roughness:document.querySelector('#roughness'),color:document.querySelector('#color'),animation:document.querySelector('#animationType'),animSpeed:document.querySelector('#animSpeed'),animAmount:document.querySelector('#animAmount')};
function selectLayer(id){if(!fields[id])return;selected=id;document.querySelector('#selectedName').textContent=fields[id].label;document.querySelectorAll('.field-btn').forEach(b=>b.classList.toggle('active',b.dataset.id===id));syncControls();}
function syncControls(){const c=fields[selected];if(!c)return;controls.text.value=c.text;for(const k of ['size','depth','x','y','scaleX','scaleY','rotZ','rotX','bend','bevel','metalness','roughness','color'])controls[k].value=c[k];controls.animation.value=c.animation;controls.animSpeed.value=c.animSpeed;controls.animAmount.value=c.animAmount;}
function syncXYOnly(){if(!fields[selected])return;controls.x.value=fields[selected].x;controls.y.value=fields[selected].y;}
let rebuildTimer;function queueRebuild(){clearTimeout(rebuildTimer);rebuildTimer=setTimeout(()=>rebuild(selected),20);}
controls.text.addEventListener('input',e=>{fields[selected].text=e.target.value||' ';queueRebuild();});['size','depth','bend','bevel','color'].forEach(k=>controls[k].addEventListener('input',e=>{fields[selected][k]=k==='color'?e.target.value:Number(e.target.value);queueRebuild();}));['metalness','roughness'].forEach(k=>controls[k].addEventListener('input',e=>{fields[selected][k]=Number(e.target.value);if(meshes[selected])meshes[selected].material[k]=fields[selected][k];}));['x','y','scaleX','scaleY','rotZ','rotX'].forEach(k=>controls[k].addEventListener('input',e=>{fields[selected][k]=Number(e.target.value);clampFieldToPoster(selected);applyBaseTransform(selected);syncXYOnly();}));controls.animation.addEventListener('change',e=>fields[selected].animation=e.target.value);controls.animSpeed.addEventListener('input',e=>fields[selected].animSpeed=Number(e.target.value));controls.animAmount.addEventListener('input',e=>fields[selected].animAmount=Number(e.target.value));
document.querySelectorAll('[data-fx]').forEach(btn=>btn.onclick=()=>{const c=fields[selected];if(btn.dataset.fx==='plastic'){c.metalness=.2;c.roughness=.18;c.bevel=Math.max(c.bevel,3);}if(btn.dataset.fx==='chrome'){c.metalness=1;c.roughness=.08;c.color='#d9e2ea';c.bevel=Math.max(c.bevel,3);}if(btn.dataset.fx==='cream'){c.metalness=.05;c.roughness=.42;c.color='#f5ead8';}syncControls();rebuild(selected);});
function applyPreset(type){Object.values(fields).forEach(c=>{if(type==='classic'){c.bend=0;c.rotX=0;c.rotZ=0;c.metalness=.15;c.roughness=.28;}if(type==='chrome'){c.metalness=1;c.roughness=.07;c.bevel=Math.max(c.bevel,4);c.color='#d9e2ea';}if(type==='warp'){c.bend=(Math.random()-.5)*1.1;c.rotX=(Math.random()-.5)*18;c.rotZ=(Math.random()-.5)*10;c.metalness=.45;c.roughness=.16;}});rebuildAll();syncControls();}
document.querySelector('#presetClassic').onclick=()=>applyPreset('classic');document.querySelector('#presetChrome').onclick=()=>applyPreset('chrome');document.querySelector('#presetWarp').onclick=()=>applyPreset('warp');
document.querySelectorAll('.palette').forEach(btn=>btn.onclick=()=>{bgState.colors=[...palettes[btn.dataset.palette]];['bg1','bg2','bg3'].forEach((id,i)=>document.querySelector('#'+id).value=bgState.colors[i]);updateBackground();});['bg1','bg2','bg3'].forEach((id,i)=>document.querySelector('#'+id).addEventListener('input',e=>{bgState.colors[i]=e.target.value;updateBackground();}));document.querySelector('#bgAngle').addEventListener('input',e=>{bgState.angle=Number(e.target.value);updateBackground();});
document.querySelector('#logoDepth').addEventListener('input',e=>{logoState.depth=Number(e.target.value);buildLogo();});document.querySelector('#logoScale').addEventListener('input',e=>{logoState.scale=Number(e.target.value);applyLogoBase();});document.querySelector('#logoAnimation').addEventListener('change',e=>logoState.animation=e.target.value);
document.querySelector('#logoUpload').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;loadImageAsTexture(file,430,125,({texture,width,height})=>{if(logoState.texture)logoState.texture.dispose();logoState.texture=texture;logoState.width=width;logoState.height=height;logoState.x=0;logoState.y=505;logoState.scale=1;document.querySelector('#logoScale').value='1';buildLogo();});});
['partnerLogo1','partnerLogo2'].forEach((id,index)=>document.querySelector('#'+id).addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;loadImageAsTexture(file,132,74,({texture,width,height})=>{const s=partnerStates[index];if(s.texture)s.texture.dispose();s.texture=texture;s.width=width;s.height=height;buildPartnerLogo(index);});}));
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let drag=null;
function pointerToPoster(ev){const rect=renderer.domElement.getBoundingClientRect();return{x:(ev.clientX-rect.left)/rect.width*POSTER_W-HALF_W,y:HALF_H-(ev.clientY-rect.top)/rect.height*POSTER_H};}
renderer.domElement.addEventListener('pointerdown',ev=>{const rect=renderer.domElement.getBoundingClientRect();pointer.x=((ev.clientX-rect.left)/rect.width)*2-1;pointer.y=-((ev.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const objects=[...Object.values(meshes),...sketchStates.map(s=>s.group).filter(Boolean)];const hits=raycaster.intersectObjects(objects,true);if(!hits.length)return;let obj=hits[0].object;while(obj.parent&&obj.parent!==scene&&!obj.userData.layerId&&!obj.userData.sketchId)obj=obj.parent;const p=pointerToPoster(ev);const layerId=obj.userData.layerId||obj.parent?.userData?.layerId;if(layerId&&fields[layerId]){selectLayer(layerId);drag={type:'text',id:layerId,dx:fields[layerId].x-p.x,dy:fields[layerId].y-p.y};renderer.domElement.setPointerCapture(ev.pointerId);return;}const sketchId=obj.userData.sketchId||obj.parent?.userData?.sketchId;if(sketchId){const s=sketchStates.find(v=>v.id===sketchId);if(s){drag={type:'sketch',id:sketchId,dx:s.x-p.x,dy:s.y-p.y};renderer.domElement.setPointerCapture(ev.pointerId);}}});
renderer.domElement.addEventListener('pointermove',ev=>{if(!drag)return;const p=pointerToPoster(ev);if(drag.type==='text'){const c=fields[drag.id];c.x=p.x+drag.dx;c.y=p.y+drag.dy;clampFieldToPoster(drag.id);applyBaseTransform(drag.id);if(selected===drag.id)syncXYOnly();}else{const s=sketchStates.find(v=>v.id===drag.id);if(!s)return;s.x=p.x+drag.dx;s.y=p.y+drag.dy;clampImageState(s);if(s.group)s.group.position.set(s.x,s.y,65);}});renderer.domElement.addEventListener('pointerup',ev=>{drag=null;try{renderer.domElement.releasePointerCapture(ev.pointerId);}catch{}});renderer.domElement.addEventListener('pointercancel',()=>drag=null);
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);}
document.querySelector('#exportPng').onclick=()=>{renderer.render(scene,camera);const base=renderer.domElement,out=document.createElement('canvas');out.width=base.width;out.height=base.height;const ctx=out.getContext('2d');ctx.drawImage(base,0,0);const overlay=document.querySelector('#partner-logo-overlay');if(overlay){const imgs=[...overlay.querySelectorAll('img')].filter(img=>img.src&&img.style.display!=='none');if(imgs.length){const baseRect=base.getBoundingClientRect(),scaleX=out.width/baseRect.width,scaleY=out.height/baseRect.height;imgs.forEach(img=>{const r=img.getBoundingClientRect();ctx.drawImage(img,(r.left-baseRect.left)*scaleX,(r.top-baseRect.top)*scaleY,r.width*scaleX,r.height*scaleY);});}}out.toBlob(blob=>blob&&downloadBlob(blob,'more-amore-poster.png'),'image/png');};
document.querySelector('#exportVideo').onclick=()=>{const canvas=renderer.domElement;if(!canvas.captureStream||typeof MediaRecorder==='undefined'){alert('Video export is not supported in this browser.');return;}const stream=canvas.captureStream(60),chunks=[];let recorder;try{recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9'});}catch{recorder=new MediaRecorder(stream);}recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>downloadBlob(new Blob(chunks,{type:recorder.mimeType||'video/webm'}),'more-amore-poster.webm');recorder.start();setTimeout(()=>recorder.stop(),VIDEO_DURATION_MS);};
const fontLoader=new FontLoader();fontLoader.load('https://cdn.jsdelivr.net/npm/three@0.180.0/examples/fonts/helvetiker_bold.typeface.json',f=>{font=f;rebuildAll();selectLayer(selected);render();},undefined,err=>{console.error(err);alert('Font load failed. Check your internet connection.');});
