import * as THREE from 'three';
import { FontLoader } from 'three/examples/jsm/loaders/FontLoader.js';
import { TextGeometry } from 'three/examples/jsm/geometries/TextGeometry.js';
import './style.css';

const POSTER_W = 1080, POSTER_H = 1350, HALF_W = 540, HALF_H = 675, SAFE_MARGIN = 86, SCALE = .56, VIDEO_DURATION_MS = 5000;
const stage=document.querySelector('#stage');const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(POSTER_W*SCALE,POSTER_H*SCALE);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.setAttribute('aria-label','Poster canvas: drag text and sketch layers');stage.appendChild(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(28,POSTER_W/POSTER_H,1,5000);camera.position.set(0,0,2707);scene.add(new THREE.AmbientLight(0xffffff,1.55));const key=new THREE.DirectionalLight(0xfff2df,4.2);key.position.set(-300,420,900);scene.add(key);const rim=new THREE.DirectionalLight(0xff48c4,3.2);rim.position.set(600,-180,700);scene.add(rim);
const bgCanvas=document.createElement('canvas');bgCanvas.width=POSTER_W;bgCanvas.height=POSTER_H;const bgTexture=new THREE.CanvasTexture(bgCanvas);bgTexture.colorSpace=THREE.SRGBColorSpace;const bg=new THREE.Mesh(new THREE.PlaneGeometry(POSTER_W,POSTER_H),new THREE.MeshBasicMaterial({map:bgTexture}));bg.position.z=-1;scene.add(bg);const palettes={amore:['#240812','#6d173b','#b77cff'],acid:['#08170d','#31ff70','#fb38ff'],night:['#03020a','#1b1456','#215dff'],sunset:['#32101d','#ff4a1a','#ffb65c']},bgState={colors:[...['#240812','#6d173b','#b77cff']],angle:135};function updateBackground(){const c=bgCanvas.getContext('2d'),r=THREE.MathUtils.degToRad(bgState.angle),cx=540,cy=675,l=Math.hypot(1080,1350)/2,g=c.createLinearGradient(cx-Math.cos(r)*l,cy-Math.sin(r)*l,cx+Math.cos(r)*l,cy+Math.sin(r)*l);g.addColorStop(0,bgState.colors[0]);g.addColorStop(.52,bgState.colors[1]);g.addColorStop(1,bgState.colors[2]);c.fillStyle=g;c.fillRect(0,0,1080,1350);bgTexture.needsUpdate=true}updateBackground();
const fields={logo:{label:'MORE AMORE TEXT',text:' ',size:52,depth:18,x:0,y:470,scaleX:2,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:3,metalness:.15,roughness:.3,color:'#fff1dc',animation:'none',animSpeed:1,animAmount:18},guest:{label:'GUEST',text:'GUEST NAME',size:85,depth:24,x:0,y:250,scaleX:1,scaleY:2,rotZ:0,rotX:0,bend:0,bevel:4,metalness:.25,roughness:.2,color:'#b77cff',animation:'none',animSpeed:1,animAmount:24},support1:{label:'ARTIST 1',text:'ARTIST 1',size:34,depth:12,x:0,y:105,scaleX:2,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:2.5,metalness:.05,roughness:.4,color:'#f5ead8',animation:'none',animSpeed:1,animAmount:18},support2:{label:'ARTIST 2',text:'ARTIST 2',size:34,depth:12,x:0,y:35,scaleX:1,scaleY:2,rotZ:0,rotX:0,bend:0,bevel:2.5,metalness:.05,roughness:.4,color:'#f5ead8',animation:'none',animSpeed:1,animAmount:18},support3:{label:'ARTIST 3',text:'ARTIST 3',size:34,depth:12,x:0,y:-35,scaleX:2,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:2.5,metalness:.05,roughness:.4,color:'#f5ead8',animation:'none',animSpeed:1,animAmount:18},venue:{label:'VENUE',text:'CLUB NAME',size:40,depth:14,x:0,y:-145,scaleX:1,scaleY:2,rotZ:0,rotX:0,bend:0,bevel:3,metalness:.15,roughness:.28,color:'#ff4a1a',animation:'none',animSpeed:1,animAmount:18},address:{label:'ADDRESS',text:'VIA INDIRIZZO, CITTÀ',size:20,depth:7,x:0,y:-235,scaleX:2,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:1.5,metalness:.1,roughness:.45,color:'#ff4a1a',animation:'none',animSpeed:1,animAmount:14},date:{label:'DATE',text:'DAY 00 MONTH',size:30,depth:12,x:-300,y:-490,scaleX:1,scaleY:2,rotZ:0,rotX:0,bend:0,bevel:2.5,metalness:.2,roughness:.28,color:'#b77cff',animation:'none',animSpeed:1,animAmount:16},time:{label:'TIME',text:'23:00 — TILL LATE',size:20,depth:7,x:-300,y:-555,scaleX:2,scaleY:1,rotZ:0,rotX:0,bend:0,bevel:1.5,metalness:.05,roughness:.4,color:'#f5ead8',animation:'none',animSpeed:1,animAmount:12}};
let artistCounter=0,infoCounter=0,sketchCounter=0,font,serifFont,selected='guest';const meshes={},clock=new THREE.Clock();function makeMaterial(c){return new THREE.MeshStandardMaterial({color:c.color,metalness:c.metalness,roughness:c.roughness,envMapIntensity:2.4})}function buildGeometry(c){const activeFont=c.fontFamily==='serifItalic'&&serifFont?serifFont:font;const g=new TextGeometry(c.text,{font:activeFont,size:c.size,depth:c.depth,curveSegments:10,bevelEnabled:c.bevel>0,bevelThickness:c.bevel*.65,bevelSize:c.bevel,bevelSegments:4});g.computeBoundingBox();const b=g.boundingBox,w=b.max.x-b.min.x,h=b.max.y-b.min.y;g.translate(-b.min.x-w/2,-b.min.y-h/2,0);const p=g.attributes.position,d=Math.max(w*w,1);for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i);p.setY(i,y+c.bend*(x*x/d)*260);if(c.fontFamily==='serifItalic')p.setX(i,x+y*.18)}p.needsUpdate=true;g.computeVertexNormals();g.computeBoundingBox();return g}function ext(id){const m=meshes[id];if(!m||!m.geometry.boundingBox)return{x:40,y:20};const b=m.geometry.boundingBox;return{x:(b.max.x-b.min.x)*Math.abs(fields[id].scaleX)/2,y:(b.max.y-b.min.y)*Math.abs(fields[id].scaleY)/2}}function clamp(id){const c=fields[id],e=ext(id),mx=Math.max(0,HALF_W-SAFE_MARGIN-Math.min(e.x,HALF_W-SAFE_MARGIN)),my=Math.max(0,HALF_H-SAFE_MARGIN-Math.min(e.y,HALF_H-SAFE_MARGIN));c.x=THREE.MathUtils.clamp(c.x,-mx,mx);c.y=THREE.MathUtils.clamp(c.y,-my,my)}function base(id){const c=fields[id],m=meshes[id];if(!m)return;m.position.set(c.x,c.y,0);m.rotation.set(THREE.MathUtils.degToRad(c.rotX),0,THREE.MathUtils.degToRad(c.rotZ));m.scale.set(c.scaleX,c.scaleY,1)}function rebuild(id){if(!font||!fields[id])return;const c=fields[id];if(meshes[id]){scene.remove(meshes[id]);meshes[id].geometry.dispose();meshes[id].material.dispose()}const g=buildGeometry(c),m=new THREE.Mesh(g,makeMaterial(c));m.userData.layerId=id;if(c.stroke){const edges=new THREE.EdgesGeometry(g,18),line=new THREE.LineSegments(edges,new THREE.LineBasicMaterial({color:0xffffff}));line.userData.layerId=id;m.add(line)}meshes[id]=m;scene.add(m);clamp(id);base(id)}function rebuildAll(){Object.keys(fields).forEach(rebuild)}
const logoState={group:null,texture:null,width:480,height:190,depth:28,scale:1,x:0,y:455,animation:'none',animSpeed:1,animAmount:20};function disposeGroup(g){if(!g)return;g.traverse(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m?.dispose?.());else o.material?.dispose?.()});scene.remove(g)}function buildLogo(){if(!logoState.texture)return;disposeGroup(logoState.group);const g=new THREE.Group(),n=Math.max(4,Math.round(logoState.depth/2));for(let i=n;i>=1;i--){const m=new THREE.Mesh(new THREE.PlaneGeometry(logoState.width,logoState.height),new THREE.MeshBasicMaterial({map:logoState.texture,transparent:true,alphaTest:.03,color:'#6f315d',side:THREE.DoubleSide}));m.position.z=-i*(logoState.depth/n);g.add(m)}const f=new THREE.Mesh(new THREE.PlaneGeometry(logoState.width,logoState.height),new THREE.MeshBasicMaterial({map:logoState.texture,transparent:true,alphaTest:.03,side:THREE.DoubleSide}));f.position.z=1;g.add(f);logoState.group=g;scene.add(g);applyLogoBase()}function applyLogoBase(){if(logoState.group){logoState.group.position.set(logoState.x,logoState.y,55);logoState.group.scale.setScalar(logoState.scale)}}function loadImageAsTexture(file,maxW,maxH,cb){const u=URL.createObjectURL(file),i=new Image();i.onload=()=>{const r=Math.min(maxW/i.naturalWidth,maxH/i.naturalHeight,1),t=new THREE.Texture(i);t.colorSpace=THREE.SRGBColorSpace;t.needsUpdate=true;cb({texture:t,width:i.naturalWidth*r,height:i.naturalHeight*r});URL.revokeObjectURL(u)};i.src=u}
const trashBg={mesh:null,texture:null,opacity:1,zoom:1,x:0,y:0,hdr:0};
const trashPrompts={
angel:'celestial marble angel statue in clouds, chrome highlights, sparkles, dreamy Y2K fantasy wallpaper, hyper HDR',
water:'shimmering electric blue water surface, hard specular sparkles, glossy Y2K wallpaper, hyper HDR',
fire:'chrome heart surrounded by dramatic flames, black background, kitsch Y2K fantasy, hyper HDR',
rose:'macro wet crimson rose covered in crystal droplets and star sparkles, romantic Y2K wallpaper, hyper HDR',
dolphin:'dolphins jumping from a glittering ocean at pink violet sunset, dreamy 2000s fantasy wallpaper, hyper HDR',
horse:'white fantasy horse running through sparkling water under rainbow clouds, glossy Y2K dreamscape, hyper HDR',
lightning:'purple lightning storm over reflective water, dramatic clouds, electric glow, hyper HDR wallpaper',
sunset:'tropical ocean sunset with palm silhouette, saturated pink orange violet sky, glossy Y2K wallpaper, hyper HDR',
space:'spiral galaxy and dense sparkling stars, deep blue cosmic wallpaper, luminous Y2K fantasy, hyper HDR',
eye:'macro human eye with iridescent glitter and star flares, glossy cyber Y2K aesthetic, hyper HDR',
heart:'transparent pink glass heart floating in cotton candy clouds, chrome reflections, sparkles, Y2K fantasy wallpaper',
statue:'close-up classical marble statue with cold blue chrome reflections and star flares, dark background, hyper HDR',
tropical:'impossibly clear tropical lagoon, palms, huge white clouds, saturated cyan water, glossy desktop wallpaper, hyper HDR',
chrome:'abstract liquid chrome folds, mirror metal, blue highlights and star flares, Y2K 3D wallpaper, hyper HDR',
windows:'nostalgic early-2000s desktop wallpaper mood, green hill blue sky clouds, retro computer UI atmosphere, dreamy Y2K core'
};
const trashLibrary=Object.fromEntries(Object.keys(trashPrompts).map(k=>[k,[]]));let trashIndex=0;
function setTrashTexture(texture){trashBg.texture?.dispose?.();trashBg.texture=texture;if(trashBg.mesh){scene.remove(trashBg.mesh);trashBg.mesh.geometry.dispose();trashBg.mesh.material.dispose()}trashBg.mesh=new THREE.Mesh(new THREE.PlaneGeometry(POSTER_W,POSTER_H),new THREE.MeshBasicMaterial({map:texture,transparent:true,opacity:trashBg.opacity,depthTest:false}));trashBg.mesh.position.z=-.5;scene.add(trashBg.mesh);applyTrashBg()}
function applyTrashBg(){if(!trashBg.mesh)return;trashBg.mesh.position.set(trashBg.x,trashBg.y,-.5);trashBg.mesh.scale.setScalar(trashBg.zoom);trashBg.mesh.material.opacity=trashBg.opacity;const v=1+trashBg.hdr*.45;trashBg.mesh.material.color.setRGB(v,v,v)}
function loadTrashUrl(url){new THREE.TextureLoader().load(url,t=>{t.colorSpace=THREE.SRGBColorSpace;setTrashTexture(t)})}
function showTrash(step=0,random=false){const tag=document.querySelector('#trashBgLibrary').value,list=trashLibrary[tag]||[];if(!list.length)return;trashIndex=random?Math.floor(Math.random()*list.length):(trashIndex+step+list.length)%list.length;loadTrashUrl(`${import.meta.env.BASE_URL}${list[trashIndex]}`)}
document.querySelector('#trashBgLibrary').onchange=()=>{trashIndex=0;showTrash()};document.querySelector('#trashPrev').onclick=()=>showTrash(-1);document.querySelector('#trashNext').onclick=()=>showTrash(1);document.querySelector('#trashRandom').onclick=()=>showTrash(0,true);
document.querySelector('#trashBgUpload').onchange=e=>{const f=e.target.files?.[0];if(!f)return;loadImageAsTexture(f,POSTER_W*2,POSTER_H*2,({texture})=>setTrashTexture(texture))};
const trashGenerate=document.querySelector('#trashGenerate'),trashGenerateStatus=document.querySelector('#trashGenerateStatus');
if(trashGenerate)trashGenerate.onclick=async()=>{const tag=document.querySelector('#trashBgLibrary').value;if(!tag||!trashPrompts[tag]){trashGenerateStatus.textContent='Choose a category first.';return}trashGenerate.disabled=true;trashGenerateStatus.textContent='GENERATING '+tag.toUpperCase()+'…';try{const res=await fetch('/api/generate-bg',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({category:tag,prompt:trashPrompts[tag],aspectRatio:'4:5'})});if(!res.ok)throw new Error(res.status===404?'endpoint not configured':'generation failed');const data=await res.json();const url=data.url||data.imageUrl;if(!url)throw new Error('no image returned');loadTrashUrl(url);trashGenerateStatus.textContent=tag.toUpperCase()+' READY ✦'}catch(err){trashGenerateStatus.textContent='Generator not connected yet — upload still works.'}finally{trashGenerate.disabled=false}};
[['trashOpacity','opacity'],['trashZoom','zoom'],['trashX','x'],['trashY','y'],['trashHdr','hdr']].forEach(([id,k])=>document.querySelector('#'+id).oninput=e=>{trashBg[k]=+e.target.value;applyTrashBg()});
const sketchStates=[],sketchList=document.querySelector('#sketchList');let selectedSketch=null;function clampImageState(s){const hw=Math.min(s.width*s.scale/2,HALF_W-SAFE_MARGIN),hh=Math.min(s.height*s.scale/2,HALF_H-SAFE_MARGIN);s.x=THREE.MathUtils.clamp(s.x,-HALF_W+SAFE_MARGIN+hw,HALF_W-SAFE_MARGIN-hw);s.y=THREE.MathUtils.clamp(s.y,-HALF_H+SAFE_MARGIN+hh,HALF_H-SAFE_MARGIN-hh)}function buildSketch(s){if(s.group)disposeGroup(s.group);const g=new THREE.Group(),geo=new THREE.PlaneGeometry(s.width,s.height,24,24),pos=geo.attributes.position;if(s.warp){for(let i=0;i<pos.count;i++){const x=pos.getX(i),y=pos.getY(i),nx=x/(s.width/2);pos.setY(i,y+s.warp*(nx*nx)*s.height*.22)}pos.needsUpdate=true}const m=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({map:s.texture,transparent:true,alphaTest:.01,side:THREE.DoubleSide,depthTest:false}));m.userData.sketchId=s.id;g.userData.sketchId=s.id;g.add(m);s.group=g;clampImageState(s);g.position.set(s.x,s.y,65);g.rotation.z=THREE.MathUtils.degToRad(s.rotation||0);g.scale.set((s.scale||1)*(s.scaleX||1),(s.scale||1)*(s.scaleY||1),1);scene.add(g)}function addSketchListItem(s){const r=document.createElement('div');r.className='sketch-item';r.innerHTML=`<span>${s.name}</span><button>×</button>`;r.querySelector('span').onclick=()=>{selectedSketch=s;syncSketchControls()};r.querySelector('button').onclick=()=>{if(selectedSketch===s)selectedSketch=null;disposeGroup(s.group);s.texture.dispose();sketchStates.splice(sketchStates.indexOf(s),1);r.remove()};sketchList.appendChild(r)}function addSketchFile(file){loadImageAsTexture(file,360,360,({texture,width,height})=>{const i=sketchCounter++,s={id:`sketch-${Date.now()}-${i}`,name:file.name,texture,width,height,scale:1,scaleX:1,scaleY:1,rotation:0,warp:0,x:-280+(i%3)*120,y:160-(i%4)*95,group:null};sketchStates.push(s);buildSketch(s);addSketchListItem(s)})}document.querySelector('#sketchUpload').addEventListener('change',e=>{[...(e.target.files||[])].forEach(addSketchFile);e.target.value=''})function syncSketchControls(){if(!selectedSketch)return;document.querySelector('#sketchScaleX').value=selectedSketch.scaleX||1;document.querySelector('#sketchScaleY').value=selectedSketch.scaleY||1;document.querySelector('#sketchRotate').value=selectedSketch.rotation||0;document.querySelector('#sketchWarp').value=selectedSketch.warp||0}
[['sketchScaleX','scaleX'],['sketchScaleY','scaleY'],['sketchRotate','rotation'],['sketchWarp','warp']].forEach(([id,k])=>document.querySelector('#'+id).oninput=e=>{if(!selectedSketch)return;selectedSketch[k]=+e.target.value;buildSketch(selectedSketch)});
document.querySelector('#sketchWide').onclick=()=>{if(!selectedSketch)return;selectedSketch.scaleX=2;selectedSketch.scaleY=1;buildSketch(selectedSketch);syncSketchControls()};document.querySelector('#sketchTall').onclick=()=>{if(!selectedSketch)return;selectedSketch.scaleX=1;selectedSketch.scaleY=2;buildSketch(selectedSketch);syncSketchControls()};

function animateObject(o,c,t,isLogo=false){if(!o)return;const sp=c.animSpeed||1,a=c.animAmount||20;if(isLogo){o.position.set(c.x,c.y,55);o.rotation.set(0,0,0);o.scale.setScalar(c.scale)}else{base(Object.keys(meshes).find(k=>meshes[k]===o))}if(c.animation==='rotateY')o.rotation.y=t*sp*1.6;else if(c.animation==='bounce')o.position.y=c.y+Math.abs(Math.sin(t*sp*2.5))*a;else if(c.animation==='wave'){o.rotation.z=Math.sin(t*sp*2.4)*THREE.MathUtils.degToRad(Math.min(a*.28,14));o.rotation.y=Math.sin(t*sp*1.8)*THREE.MathUtils.degToRad(Math.min(a*.16,8));}}function render(){const t=clock.getElapsedTime();Object.entries(meshes).forEach(([id,m])=>animateObject(m,fields[id],t));animateObject(logoState.group,logoState,t,true);renderer.render(scene,camera);requestAnimationFrame(render)}
const fieldsEl=document.querySelector('#fields');function addFieldButton(id){const c=fields[id],b=document.createElement('button');b.className='field-btn';b.dataset.id=id;b.innerHTML=`<span>${c.label}</span><span class="field-key">${id}</span>`;b.onclick=()=>selectLayer(id);fieldsEl.appendChild(b)}Object.keys(fields).forEach(addFieldButton);function createDynamicField(type){const a=type==='artist',n=a?++artistCounter:++infoCounter,id=`${type}${Date.now()}${n}`;fields[id]={label:`${a?'ARTISTA':'INFO'} ${n}`,text:`${a?'ARTISTA':'INFO'} ${n}`,size:a?41:24,depth:a?14:8,x:0,y:a?145-n*48:-285-n*48,scaleX:a?2:1,scaleY:a?1:2,rotZ:0,rotX:0,bend:0,bevel:2,metalness:.05,roughness:.4,color:'#f5ead8',animation:'none',animSpeed:1,animAmount:16};addFieldButton(id);rebuild(id);selectLayer(id)}document.querySelector('#addArtist').onclick=()=>createDynamicField('artist');document.querySelector('#addInfo').onclick=()=>createDynamicField('info');
const controls={text:document.querySelector('#textInput'),fontFamily:document.querySelector('#fontFamily'),stroke:document.querySelector('#textStroke'),size:document.querySelector('#size'),depth:document.querySelector('#depth'),x:document.querySelector('#x'),y:document.querySelector('#y'),scaleX:document.querySelector('#scaleX'),scaleY:document.querySelector('#scaleY'),rotZ:document.querySelector('#rotZ'),rotX:document.querySelector('#rotX'),bend:document.querySelector('#bend'),bevel:document.querySelector('#bevel'),metalness:document.querySelector('#metalness'),roughness:document.querySelector('#roughness'),color:document.querySelector('#color'),animation:document.querySelector('#animationType'),animSpeed:document.querySelector('#animSpeed'),animAmount:document.querySelector('#animAmount')};function selectLayer(id){if(!fields[id])return;selected=id;document.querySelector('#selectedName').textContent=fields[id].label;document.querySelectorAll('.field-btn').forEach(b=>b.classList.toggle('active',b.dataset.id===id));syncControls()}function syncControls(){const c=fields[selected];controls.text.value=c.text;controls.fontFamily.value=c.fontFamily||'sans';controls.stroke.checked=!!c.stroke;['size','depth','x','y','scaleX','scaleY','rotZ','rotX','bend','bevel','metalness','roughness','color'].forEach(k=>controls[k].value=c[k]);controls.animation.value=c.animation;controls.animSpeed.value=c.animSpeed;controls.animAmount.value=c.animAmount}function queue(){setTimeout(()=>rebuild(selected),0)}controls.text.oninput=e=>{fields[selected].text=e.target.value||' ';queue()};controls.fontFamily.onchange=e=>{fields[selected].fontFamily=e.target.value;queue()};controls.stroke.onchange=e=>{fields[selected].stroke=e.target.checked;queue()};['size','depth','bend','bevel','color'].forEach(k=>controls[k].oninput=e=>{fields[selected][k]=k==='color'?e.target.value:+e.target.value;queue()});['metalness','roughness'].forEach(k=>controls[k].oninput=e=>{fields[selected][k]=+e.target.value;if(meshes[selected])meshes[selected].material[k]=+e.target.value});['x','y','scaleX','scaleY','rotZ','rotX'].forEach(k=>controls[k].oninput=e=>{fields[selected][k]=+e.target.value;clamp(selected);base(selected)});controls.animation.onchange=e=>fields[selected].animation=e.target.value;controls.animSpeed.oninput=e=>fields[selected].animSpeed=+e.target.value;controls.animAmount.oninput=e=>fields[selected].animAmount=+e.target.value;
document.querySelectorAll('[data-fx]').forEach(b=>b.onclick=()=>{const c=fields[selected];if(b.dataset.fx==='plastic'){c.metalness=.2;c.roughness=.18}if(b.dataset.fx==='chrome'){c.metalness=1;c.roughness=.08;c.color='#d9e2ea'}if(b.dataset.fx==='cream'){c.metalness=.05;c.roughness=.42;c.color='#f5ead8'}syncControls();rebuild(selected)});function applyPreset(t){const ids=Object.keys(fields);ids.forEach((id,index)=>{const c=fields[id];if(t==='classic'){c.bend=0;c.rotX=0;c.rotZ=0;c.scaleX=1;c.scaleY=1;if(id==='guest'){c.size=85;c.scaleX=.9}}if(t==='chrome'){c.metalness=.82;c.roughness=.18;c.color='#e8edf2';c.bevel=Math.max(c.bevel,3);c.bend=0;c.rotX=0;c.rotZ=0}if(t==='bubble'){c.metalness=.08;c.roughness=.12;c.bevel=Math.max(5,Math.min(10,c.size*.12));c.depth=Math.max(c.depth,Math.min(30,c.size*.34));c.scaleX=Math.max(c.scaleX,1.04);c.scaleY=Math.max(c.scaleY,1.12);c.bend=0}if(t==='warp'){const dx=c.x/HALF_W,dy=c.y/HALF_H,r=Math.min(1,Math.hypot(dx,dy));const magnify=1+.20*(1-r);c.scaleX=magnify*(1+.12*Math.abs(dx));c.scaleY=magnify;c.rotZ=dx*4;c.rotX=-dy*10;c.bend=-.22*(1-r)}});rebuildAll();syncControls()}document.querySelector('#presetClassic').onclick=()=>applyPreset('classic');document.querySelector('#presetChrome').onclick=()=>applyPreset('chrome');document.querySelector('#presetWarp').onclick=()=>applyPreset('warp');document.querySelector('#presetBubble')?.addEventListener('click',()=>applyPreset('bubble'));document.querySelectorAll('.palette').forEach(b=>b.onclick=()=>{bgState.colors=[...palettes[b.dataset.palette]];updateBackground()});['bg1','bg2','bg3'].forEach((id,i)=>document.querySelector('#'+id).oninput=e=>{bgState.colors[i]=e.target.value;updateBackground()});document.querySelector('#bgAngle').oninput=e=>{bgState.angle=+e.target.value;updateBackground()};document.querySelector('#logoDepth').oninput=e=>{logoState.depth=+e.target.value;buildLogo()};document.querySelector('#logoScale').oninput=e=>{logoState.scale=+e.target.value;applyLogoBase()};document.querySelector('#logoAnimation').onchange=e=>logoState.animation=e.target.value;document.querySelector('#logoUpload').onchange=e=>{const f=e.target.files?.[0];if(f)loadImageAsTexture(f,430,125,({texture,width,height})=>{logoState.texture?.dispose();logoState.texture=texture;logoState.width=width;logoState.height=height;logoState.x=0;logoState.y=505;logoState.scale=1;buildLogo()})};
// IMPORTANT: partnerLogo1/partnerLogo2 are NOT handled in Three.js here.
// partner-overlay.js is the only renderer, preventing duplicate logos in the canvas center.
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let drag=null;function pointerToPoster(e){const r=renderer.domElement.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*1080-540,y:675-(e.clientY-r.top)/r.height*1350}}renderer.domElement.onpointerdown=e=>{const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);const h=raycaster.intersectObjects([...Object.values(meshes),...sketchStates.map(s=>s.group).filter(Boolean)],true);if(!h.length)return;let o=h[0].object;while(o.parent&&o.parent!==scene&&!o.userData.layerId&&!o.userData.sketchId)o=o.parent;const p=pointerToPoster(e),id=o.userData.layerId||o.parent?.userData?.layerId;if(id){selectLayer(id);drag={type:'text',id,dx:fields[id].x-p.x,dy:fields[id].y-p.y};return}const sid=o.userData.sketchId||o.parent?.userData?.sketchId;if(sid){const s=sketchStates.find(x=>x.id===sid);selectedSketch=s;syncSketchControls();drag={type:'sketch',id:sid,dx:s.x-p.x,dy:s.y-p.y}}};renderer.domElement.onpointermove=e=>{if(!drag)return;const p=pointerToPoster(e);if(drag.type==='text'){const c=fields[drag.id];c.x=p.x+drag.dx;c.y=p.y+drag.dy;clamp(drag.id);base(drag.id)}else{const s=sketchStates.find(x=>x.id===drag.id);s.x=p.x+drag.dx;s.y=p.y+drag.dy;clampImageState(s);s.group.position.set(s.x,s.y,65)}};renderer.domElement.onpointerup=()=>drag=null;
function downloadBlob(b,n){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function renderExportFrame(width,height,cb){const oldSize=new THREE.Vector2();renderer.getSize(oldSize);const oldRatio=renderer.getPixelRatio();renderer.setPixelRatio(1);renderer.setSize(width,height,false);renderer.render(scene,camera);cb();renderer.setSize(oldSize.x,oldSize.y,false);renderer.setPixelRatio(oldRatio)}
document.querySelector('#exportPng').onclick=()=>renderExportFrame(3240,4050,()=>{const out=document.createElement('canvas');out.width=3240;out.height=4050;const ctx=out.getContext('2d');ctx.drawImage(renderer.domElement,0,0,out.width,out.height);const defaultLogo=document.querySelector('#more-amore-default-logo');if(defaultLogo&&defaultLogo.style.display!=='none'&&defaultLogo.complete&&defaultLogo.naturalWidth){const maxW=430*3,maxH=150*3,safeY=86*3,ratio=defaultLogo.naturalWidth/defaultLogo.naturalHeight;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio}ctx.drawImage(defaultLogo,(out.width-w)/2,safeY+(maxH-h)/2,w,h)}window.dispatchEvent(new CustomEvent('more-amore:composite-export',{detail:{ctx,width:out.width,height:out.height}}));out.toBlob(b=>downloadBlob(b,'more-amore-poster-4x5-3x.png'),'image/png')});
document.querySelector('#exportVideo').onclick=()=>{renderExportFrame(1080,1350,()=>{const stream=renderer.domElement.captureStream(60),chunks=[];const mp4=MediaRecorder.isTypeSupported('video/mp4;codecs=avc1')?'video/mp4;codecs=avc1':(MediaRecorder.isTypeSupported('video/mp4')?'video/mp4':'video/webm;codecs=vp9');const rec=new MediaRecorder(stream,{mimeType:mp4,videoBitsPerSecond:12000000});rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const isMp4=mp4.startsWith('video/mp4');downloadBlob(new Blob(chunks,{type:mp4}),isMp4?'more-amore-poster-5s.mp4':'more-amore-poster-5s.webm')};rec.start();setTimeout(()=>rec.stop(),VIDEO_DURATION_MS)})};
const fontLoader=new FontLoader();fontLoader.load('https://cdn.jsdelivr.net/npm/three@0.180.0/examples/fonts/helvetiker_bold.typeface.json',f=>{font=f;fontLoader.load('https://cdn.jsdelivr.net/npm/three@0.180.0/examples/fonts/droid/droid_serif_regular.typeface.json',sf=>{serifFont=sf;rebuildAll();selectLayer('guest');render()},undefined,()=>{rebuildAll();selectLayer('guest');render()})});